export App from './App/App';
// export Chat from './Chat/Chat';
// export Widgets from './Widgets/Widgets';
// export Login from './Login/Login';
// export LoginSuccess from './LoginSuccess/LoginSuccess';
// export Survey from './Survey/Survey';
export Home from './Home/Home';
export Station from './Station/Station';
export Train from './Train/Train';
export TrainsBetween from './TrainsBetween/TrainsBetween';
export PNRStatus from './PNRStatus/PNRStatus';
export About from './About/About';
export NotFound from './NotFound/NotFound';
