version: '2'

services:
  trains:
    build: .
    image: sauravskumar/trains
    container_name: trains
    command: bash -c "API_HOST=192.168.43.216 HOST=192.168.43.216 npm run dev"
    depends_on:
      - mongo
      - neo4j
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./static/files:/usr/src/app/static/files
    ports:
      - 3000:3000
      - 3001:3001
      - 3030:3030
    environment:
        NODE_ENV: development

  mongo:
    image: mongo
    container_name: trains_mongo
    volumes:
      - /data/docker/trains_mongo:/data/db
      - /usr/src/app/node_modules

  neo4j:
    image: neo4j
    container_name: trains_neo4j
    volumes:
      - /data/docker/trains_neo4j:/data