version: '2'

services:
  trains:
    build: .
    image: sauravskumar/trains
    container_name: trains
    command: bash -c "rm -rf /root/.pm2 && npm run start"
    depends_on:
      - neo4j
      - mongo

  mongo:
    image: mongo
    container_name: trains_mongo
    volumes:
      - /data/docker/trains_mongo:/data/db

  neo4j:
    image: neo4j
    container_name: trains_neo4j
    volumes:
      - /data/docker/trains_neo4j:/data
    #environment:
    #  NEO4J_dbms_memory_pagecache_size: 200M
    #  NEO4J_dbms_memory_heap_maxSize: 200M