version: '2'

services:
  trains:
    image: sauravskumar/trains
    container_name: trains
    command: npm run dev
    depends_on:
      - neo4j
    volumes:
      - .:/usr/src/app
    ports:
      - 4000:4000
      - 4001:4001
      - 4030:4030
  mongo:
    image: mongo
    container_name: trains_mongo
    volumes:
      - /data/docker/trains_mongo:/data/db
  neo4j:
    image: neo4j
    container_name: trains_neo4j
    volumes:
      - /data/docker/trains_neo4j:/data