version: '2'

services:
  trains:
    images: sauravskumar/trains
    container_name: trains
  mongo:
    images: sauravskumar/trains_mongo
    container_name: trains_mongo
    volumes:
      - /data/docker/trains_mongo:/data/db