_variable_1470465209025 = [{
  trainDataFound: "trainRunningDataFound",
  trainNo: "18111",
  trainName: "TATA - YPR EXP",
  from: "TATA",
  to: "YPR",
  schArrTime: "17:55",
  schDepTime: "18:35",
  dayCnt: 2,
  idTrainDef: "400054532",
  runsOn: "0000100",
  runsOnDays: getDaysOfRunString("0000100"),
  trainType: "MEX",
  prfFlag: "0",
  vldFrm: "30 Jun 2016",
  vldTo: "-",
  trnName: function () {
    return _LANG == "en-us" ? "TATA - YPR EXP" : "टाटानगर यशवंतपुर एक्सप्रेस"
  },
  trainSchedule: {
    stations: [{
      stnCode: "TATA",
      arrTime: "00:00",
      depTime: "18:35",
      dayCnt: 0,
      distance: 0,
      pfNo: 0
    }, {stnCode: "CKP", arrTime: "19:30", depTime: "19:32", dayCnt: 0, distance: 62, pfNo: 0}, {
      stnCode: "ROU",
      arrTime: "20:56",
      depTime: "21:01",
      dayCnt: 0,
      distance: 161,
      pfNo: 0
    }, {stnCode: "JSG", arrTime: "22:35", depTime: "22:40", dayCnt: 0, distance: 263, pfNo: 0}, {
      stnCode: "SBP",
      arrTime: "23:25",
      depTime: "23:35",
      dayCnt: 0,
      distance: 311,
      pfNo: 0
    }, {stnCode: "BRGA", arrTime: "00:18", depTime: "00:20", dayCnt: 1, distance: 354, pfNo: 0}, {
      stnCode: "BLGR",
      arrTime: "01:15",
      depTime: "01:20",
      dayCnt: 1,
      distance: 429,
      pfNo: 0
    }, {stnCode: "TIG", arrTime: "02:45", depTime: "02:55", dayCnt: 1, distance: 493, pfNo: 0}, {
      stnCode: "KSNG",
      arrTime: "03:10",
      depTime: "03:12",
      dayCnt: 1,
      distance: 506,
      pfNo: 0
    }, {stnCode: "MNGD", arrTime: "04:15", depTime: "04:17", dayCnt: 1, distance: 578, pfNo: 0}, {
      stnCode: "RGDA",
      arrTime: "06:15",
      depTime: "06:30",
      dayCnt: 1,
      distance: 632,
      pfNo: 0
    }, {stnCode: "PVP", arrTime: "07:10", depTime: "07:12", dayCnt: 1, distance: 679, pfNo: 0}, {
      stnCode: "VBL",
      arrTime: "07:33",
      depTime: "07:35",
      dayCnt: 1,
      distance: 703,
      pfNo: 0
    }, {stnCode: "VZM", arrTime: "08:25", depTime: "08:30", dayCnt: 1, distance: 756, pfNo: 0}, {
      stnCode: "VSKP",
      arrTime: "09:35",
      depTime: "09:55",
      dayCnt: 1,
      distance: 817,
      pfNo: 0
    }, {stnCode: "SLO", arrTime: "11:59", depTime: "12:01", dayCnt: 1, distance: 968, pfNo: 0}, {
      stnCode: "RJY",
      arrTime: "12:55",
      depTime: "12:57",
      dayCnt: 1,
      distance: 1018,
      pfNo: 0
    }, {stnCode: "EE", arrTime: "13:56", depTime: "13:58", dayCnt: 1, distance: 1108, pfNo: 0}, {
      stnCode: "BZA",
      arrTime: "15:30",
      depTime: "15:45",
      dayCnt: 1,
      distance: 1168,
      pfNo: 0
    }, {stnCode: "KMT", arrTime: "16:54", depTime: "16:55", dayCnt: 1, distance: 1261, pfNo: 0}, {
      stnCode: "WL",
      arrTime: "19:06",
      depTime: "19:08",
      dayCnt: 1,
      distance: 1369,
      pfNo: 0
    }, {stnCode: "MLY", arrTime: "21:45", depTime: "21:46", dayCnt: 1, distance: 1522, pfNo: 0}, {
      stnCode: "SC",
      arrTime: "22:20",
      depTime: "22:30",
      dayCnt: 1,
      distance: 1528,
      pfNo: 0
    }, {stnCode: "LPI", arrTime: "23:04", depTime: "23:05", dayCnt: 1, distance: 1551, pfNo: 0}, {
      stnCode: "VKB",
      arrTime: "23:45",
      depTime: "23:46",
      dayCnt: 1,
      distance: 1600,
      pfNo: 0
    }, {stnCode: "TDU", arrTime: "01:40", depTime: "01:41", dayCnt: 2, distance: 1642, pfNo: 0}, {
      stnCode: "YG",
      arrTime: "03:43",
      depTime: "03:45",
      dayCnt: 2,
      distance: 1751,
      pfNo: 0
    }, {stnCode: "RC", arrTime: "05:13", depTime: "05:15", dayCnt: 2, distance: 1820, pfNo: 0}, {
      stnCode: "MALM",
      arrTime: "06:13",
      depTime: "06:15",
      dayCnt: 2,
      distance: 1848,
      pfNo: 0
    }, {stnCode: "AD", arrTime: "06:43", depTime: "06:45", dayCnt: 2, distance: 1889, pfNo: 0}, {
      stnCode: "GTL",
      arrTime: "07:50",
      depTime: "08:15",
      dayCnt: 2,
      distance: 1941,
      pfNo: 0
    }, {stnCode: "BAY", arrTime: "09:48", depTime: "09:50", dayCnt: 2, distance: 1991, pfNo: 0}, {
      stnCode: "MOMU",
      arrTime: "11:26",
      depTime: "11:27",
      dayCnt: 2,
      distance: 2059,
      pfNo: 0
    }, {stnCode: "CHKE", arrTime: "12:09", depTime: "12:10", dayCnt: 2, distance: 2107, pfNo: 0}, {
      stnCode: "CTA",
      arrTime: "12:43",
      depTime: "12:45",
      dayCnt: 2,
      distance: 2142,
      pfNo: 0
    }, {stnCode: "RRB", arrTime: "14:24", depTime: "14:25", dayCnt: 2, distance: 2244, pfNo: 0}, {
      stnCode: "DRU",
      arrTime: "14:34",
      depTime: "14:35",
      dayCnt: 2,
      distance: 2250,
      pfNo: 0
    }, {stnCode: "ASK", arrTime: "15:05", depTime: "15:10", dayCnt: 2, distance: 2289, pfNo: 0}, {
      stnCode: "TK",
      arrTime: "16:18",
      depTime: "16:20",
      dayCnt: 2,
      distance: 2385,
      pfNo: 0
    }, {stnCode: "BAW", arrTime: "17:14", depTime: "17:15", dayCnt: 2, distance: 2444, pfNo: 0}, {
      stnCode: "YPR",
      arrTime: "17:55",
      depTime: "00:00",
      dayCnt: 2,
      distance: 2452,
      pfNo: 0
    }]
  },
  rakes: [{
    startDate: "4 Aug 2016",
    startDayDiff: "-2",
    departed: true,
    curStn: "THKU",
    terminated: false,
    idMsg: "0",
    cncldFrmStn: "",
    cncldToStn: "",
    totalJourney: "1 day 17 hrs 19 min",
    lastUpdated: "6 Aug 2016 11:55",
    stations: [{
      stnCode: "TATA",
      idTrnSch: "3372208",
      actArr: "00:00",
      actDep: "18:35",
      dayCnt: 0,
      schArrTime: "00:00",
      schDepTime: "18:35",
      schDayCnt: 0,
      delayArr: 0,
      delayDep: 0,
      arr: false,
      dep: true,
      distance: 0,
      journeyDate: "4 Aug 2016",
      actArrDate: "4 Aug 2016",
      actDepDate: "4 Aug 2016",
      dayDiff: "-2",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "CKP",
      idTrnSch: "3372209",
      actArr: "19:33",
      actDep: "19:35",
      dayCnt: 0,
      schArrTime: "19:30",
      schDepTime: "19:32",
      schDayCnt: 0,
      delayArr: 3,
      delayDep: 3,
      arr: true,
      dep: true,
      distance: 62,
      journeyDate: "4 Aug 2016",
      actArrDate: "4 Aug 2016",
      actDepDate: "4 Aug 2016",
      dayDiff: "-2",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "ROU",
      idTrnSch: "3372210",
      actArr: "21:02",
      actDep: "21:07",
      dayCnt: 0,
      schArrTime: "20:56",
      schDepTime: "21:01",
      schDayCnt: 0,
      delayArr: 6,
      delayDep: 6,
      arr: true,
      dep: true,
      distance: 161,
      journeyDate: "4 Aug 2016",
      actArrDate: "4 Aug 2016",
      actDepDate: "4 Aug 2016",
      dayDiff: "-2",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "JSG",
      idTrnSch: "3372211",
      actArr: "22:30",
      actDep: "22:40",
      dayCnt: 0,
      schArrTime: "22:35",
      schDepTime: "22:40",
      schDayCnt: 0,
      delayArr: -5,
      delayDep: 0,
      arr: true,
      dep: true,
      distance: 263,
      journeyDate: "4 Aug 2016",
      actArrDate: "4 Aug 2016",
      actDepDate: "4 Aug 2016",
      dayDiff: "-2",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "SBP",
      idTrnSch: "3372212",
      actArr: "23:45",
      actDep: "23:55",
      dayCnt: 0,
      schArrTime: "23:25",
      schDepTime: "23:35",
      schDayCnt: 0,
      delayArr: 20,
      delayDep: 20,
      arr: true,
      dep: true,
      distance: 311,
      journeyDate: "4 Aug 2016",
      actArrDate: "4 Aug 2016",
      actDepDate: "4 Aug 2016",
      dayDiff: "-2",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "BRGA",
      idTrnSch: "3372213",
      actArr: "00:28",
      actDep: "00:33",
      dayCnt: 1,
      schArrTime: "00:18",
      schDepTime: "00:20",
      schDayCnt: 1,
      delayArr: 10,
      delayDep: 13,
      arr: true,
      dep: true,
      distance: 354,
      journeyDate: "5 Aug 2016",
      actArrDate: "5 Aug 2016",
      actDepDate: "5 Aug 2016",
      dayDiff: "-1",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "BLGR",
      idTrnSch: "3372214",
      actArr: "01:38",
      actDep: "01:48",
      dayCnt: 1,
      schArrTime: "01:15",
      schDepTime: "01:20",
      schDayCnt: 1,
      delayArr: 23,
      delayDep: 28,
      arr: true,
      dep: true,
      distance: 429,
      journeyDate: "5 Aug 2016",
      actArrDate: "5 Aug 2016",
      actDepDate: "5 Aug 2016",
      dayDiff: "-1",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "TIG",
      idTrnSch: "3372215",
      actArr: "03:08",
      actDep: "03:35",
      dayCnt: 1,
      schArrTime: "02:45",
      schDepTime: "02:55",
      schDayCnt: 1,
      delayArr: 23,
      delayDep: 40,
      arr: true,
      dep: true,
      distance: 493,
      journeyDate: "5 Aug 2016",
      actArrDate: "5 Aug 2016",
      actDepDate: "5 Aug 2016",
      dayDiff: "-1",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "KSNG",
      idTrnSch: "3372216",
      actArr: "03:53",
      actDep: "03:55",
      dayCnt: 1,
      schArrTime: "03:10",
      schDepTime: "03:12",
      schDayCnt: 1,
      delayArr: 43,
      delayDep: 43,
      arr: true,
      dep: true,
      distance: 506,
      journeyDate: "5 Aug 2016",
      actArrDate: "5 Aug 2016",
      actDepDate: "5 Aug 2016",
      dayDiff: "-1",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "MNGD",
      idTrnSch: "3372217",
      actArr: "05:20",
      actDep: "05:22",
      dayCnt: 1,
      schArrTime: "04:15",
      schDepTime: "04:17",
      schDayCnt: 1,
      delayArr: 65,
      delayDep: 65,
      arr: true,
      dep: true,
      distance: 578,
      journeyDate: "5 Aug 2016",
      actArrDate: "5 Aug 2016",
      actDepDate: "5 Aug 2016",
      dayDiff: "-1",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "RGDA",
      idTrnSch: "3372218",
      actArr: "06:40",
      actDep: "07:00",
      dayCnt: 1,
      schArrTime: "06:15",
      schDepTime: "06:30",
      schDayCnt: 1,
      delayArr: 25,
      delayDep: 30,
      arr: true,
      dep: true,
      distance: 632,
      journeyDate: "5 Aug 2016",
      actArrDate: "5 Aug 2016",
      actDepDate: "5 Aug 2016",
      dayDiff: "-1",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "PVP",
      idTrnSch: "3372219",
      actArr: "07:41",
      actDep: "07:43",
      dayCnt: 1,
      schArrTime: "07:10",
      schDepTime: "07:12",
      schDayCnt: 1,
      delayArr: 31,
      delayDep: 31,
      arr: true,
      dep: true,
      distance: 679,
      journeyDate: "5 Aug 2016",
      actArrDate: "5 Aug 2016",
      actDepDate: "5 Aug 2016",
      dayDiff: "-1",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "VBL",
      idTrnSch: "3372220",
      actArr: "08:05",
      actDep: "08:08",
      dayCnt: 1,
      schArrTime: "07:33",
      schDepTime: "07:35",
      schDayCnt: 1,
      delayArr: 32,
      delayDep: 33,
      arr: true,
      dep: true,
      distance: 703,
      journeyDate: "5 Aug 2016",
      actArrDate: "5 Aug 2016",
      actDepDate: "5 Aug 2016",
      dayDiff: "-1",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "VZM",
      idTrnSch: "3372221",
      actArr: "08:50",
      actDep: "08:55",
      dayCnt: 1,
      schArrTime: "08:25",
      schDepTime: "08:30",
      schDayCnt: 1,
      delayArr: 25,
      delayDep: 25,
      arr: true,
      dep: true,
      distance: 756,
      journeyDate: "5 Aug 2016",
      actArrDate: "5 Aug 2016",
      actDepDate: "5 Aug 2016",
      dayDiff: "-1",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "VSKP",
      idTrnSch: "3372222",
      actArr: "10:05",
      actDep: "10:10",
      dayCnt: 1,
      schArrTime: "09:35",
      schDepTime: "09:55",
      schDayCnt: 1,
      delayArr: 30,
      delayDep: 15,
      arr: true,
      dep: true,
      distance: 817,
      journeyDate: "5 Aug 2016",
      actArrDate: "5 Aug 2016",
      actDepDate: "5 Aug 2016",
      dayDiff: "-1",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "SLO",
      idTrnSch: "3372223",
      actArr: "12:44",
      actDep: "12:46",
      dayCnt: 1,
      schArrTime: "11:59",
      schDepTime: "12:01",
      schDayCnt: 1,
      delayArr: 45,
      delayDep: 45,
      arr: true,
      dep: true,
      distance: 968,
      journeyDate: "5 Aug 2016",
      actArrDate: "5 Aug 2016",
      actDepDate: "5 Aug 2016",
      dayDiff: "-1",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "RJY",
      idTrnSch: "3372224",
      actArr: "13:38",
      actDep: "13:40",
      dayCnt: 1,
      schArrTime: "12:55",
      schDepTime: "12:57",
      schDayCnt: 1,
      delayArr: 43,
      delayDep: 43,
      arr: true,
      dep: true,
      distance: 1018,
      journeyDate: "5 Aug 2016",
      actArrDate: "5 Aug 2016",
      actDepDate: "5 Aug 2016",
      dayDiff: "-1",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "EE",
      idTrnSch: "3372225",
      actArr: "14:54",
      actDep: "14:56",
      dayCnt: 1,
      schArrTime: "13:56",
      schDepTime: "13:58",
      schDayCnt: 1,
      delayArr: 58,
      delayDep: 58,
      arr: true,
      dep: true,
      distance: 1108,
      journeyDate: "5 Aug 2016",
      actArrDate: "5 Aug 2016",
      actDepDate: "5 Aug 2016",
      dayDiff: "-1",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "BZA",
      idTrnSch: "3372226",
      actArr: "15:43",
      actDep: "15:58",
      dayCnt: 1,
      schArrTime: "15:30",
      schDepTime: "15:45",
      schDayCnt: 1,
      delayArr: 13,
      delayDep: 13,
      arr: false,
      dep: false,
      distance: 1168,
      journeyDate: "5 Aug 2016",
      actArrDate: "5 Aug 2016",
      actDepDate: "5 Aug 2016",
      dayDiff: "-1",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: true,
      updWaitngDep: true,
      pfNo: 0
    }, {
      stnCode: "KMT",
      idTrnSch: "3372227",
      actArr: "17:43",
      actDep: "17:45",
      dayCnt: 1,
      schArrTime: "16:54",
      schDepTime: "16:55",
      schDayCnt: 1,
      delayArr: 49,
      delayDep: 50,
      arr: true,
      dep: true,
      distance: 1261,
      journeyDate: "5 Aug 2016",
      actArrDate: "5 Aug 2016",
      actDepDate: "5 Aug 2016",
      dayDiff: "-1",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "WL",
      idTrnSch: "3372228",
      actArr: "19:10",
      actDep: "19:20",
      dayCnt: 1,
      schArrTime: "19:06",
      schDepTime: "19:08",
      schDayCnt: 1,
      delayArr: 4,
      delayDep: 12,
      arr: true,
      dep: true,
      distance: 1369,
      journeyDate: "5 Aug 2016",
      actArrDate: "5 Aug 2016",
      actDepDate: "5 Aug 2016",
      dayDiff: "-1",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "MLY",
      idTrnSch: "3372229",
      actArr: "22:00",
      actDep: "22:01",
      dayCnt: 1,
      schArrTime: "21:45",
      schDepTime: "21:46",
      schDayCnt: 1,
      delayArr: 15,
      delayDep: 15,
      arr: true,
      dep: true,
      distance: 1522,
      journeyDate: "5 Aug 2016",
      actArrDate: "5 Aug 2016",
      actDepDate: "5 Aug 2016",
      dayDiff: "-1",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "SC",
      idTrnSch: "3372230",
      actArr: "22:22",
      actDep: "22:45",
      dayCnt: 1,
      schArrTime: "22:20",
      schDepTime: "22:30",
      schDayCnt: 1,
      delayArr: 2,
      delayDep: 15,
      arr: true,
      dep: true,
      distance: 1528,
      journeyDate: "5 Aug 2016",
      actArrDate: "5 Aug 2016",
      actDepDate: "5 Aug 2016",
      dayDiff: "-1",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 5
    }, {
      stnCode: "LPI",
      idTrnSch: "3372231",
      actArr: "23:28",
      actDep: "23:52",
      dayCnt: 1,
      schArrTime: "23:04",
      schDepTime: "23:05",
      schDayCnt: 1,
      delayArr: 24,
      delayDep: 47,
      arr: true,
      dep: true,
      distance: 1551,
      journeyDate: "5 Aug 2016",
      actArrDate: "5 Aug 2016",
      actDepDate: "5 Aug 2016",
      dayDiff: "-1",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "VKB",
      idTrnSch: "3372232",
      actArr: "00:37",
      actDep: "00:38",
      dayCnt: 2,
      schArrTime: "23:45",
      schDepTime: "23:46",
      schDayCnt: 1,
      delayArr: 52,
      delayDep: 52,
      arr: true,
      dep: true,
      distance: 1600,
      journeyDate: "5 Aug 2016",
      actArrDate: "6 Aug 2016",
      actDepDate: "6 Aug 2016",
      dayDiff: "-1",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "TDU",
      idTrnSch: "3372233",
      actArr: "01:52",
      actDep: "01:53",
      dayCnt: 2,
      schArrTime: "01:40",
      schDepTime: "01:41",
      schDayCnt: 2,
      delayArr: 12,
      delayDep: 12,
      arr: true,
      dep: true,
      distance: 1642,
      journeyDate: "6 Aug 2016",
      actArrDate: "6 Aug 2016",
      actDepDate: "6 Aug 2016",
      dayDiff: "0",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "YG",
      idTrnSch: "3372234",
      actArr: "04:02",
      actDep: "04:03",
      dayCnt: 2,
      schArrTime: "03:43",
      schDepTime: "03:45",
      schDayCnt: 2,
      delayArr: 19,
      delayDep: 18,
      arr: true,
      dep: true,
      distance: 1751,
      journeyDate: "6 Aug 2016",
      actArrDate: "6 Aug 2016",
      actDepDate: "6 Aug 2016",
      dayDiff: "0",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 1
    }, {
      stnCode: "RC",
      idTrnSch: "3372235",
      actArr: "05:00",
      actDep: "05:15",
      dayCnt: 2,
      schArrTime: "05:13",
      schDepTime: "05:15",
      schDayCnt: 2,
      delayArr: -13,
      delayDep: 0,
      arr: true,
      dep: true,
      distance: 1820,
      journeyDate: "6 Aug 2016",
      actArrDate: "6 Aug 2016",
      actDepDate: "6 Aug 2016",
      dayDiff: "0",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "MALM",
      idTrnSch: "3372236",
      actArr: "06:25",
      actDep: "06:40",
      dayCnt: 2,
      schArrTime: "06:13",
      schDepTime: "06:15",
      schDayCnt: 2,
      delayArr: 12,
      delayDep: 25,
      arr: true,
      dep: true,
      distance: 1848,
      journeyDate: "6 Aug 2016",
      actArrDate: "6 Aug 2016",
      actDepDate: "6 Aug 2016",
      dayDiff: "0",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 1
    }, {
      stnCode: "AD",
      idTrnSch: "3372237",
      actArr: "07:18",
      actDep: "07:20",
      dayCnt: 2,
      schArrTime: "06:43",
      schDepTime: "06:45",
      schDayCnt: 2,
      delayArr: 35,
      delayDep: 35,
      arr: true,
      dep: true,
      distance: 1889,
      journeyDate: "6 Aug 2016",
      actArrDate: "6 Aug 2016",
      actDepDate: "6 Aug 2016",
      dayDiff: "0",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 1
    }, {
      stnCode: "GTL",
      idTrnSch: "3372238",
      actArr: "08:10",
      actDep: "08:55",
      dayCnt: 2,
      schArrTime: "07:50",
      schDepTime: "08:15",
      schDayCnt: 2,
      delayArr: 20,
      delayDep: 40,
      arr: true,
      dep: true,
      distance: 1941,
      journeyDate: "6 Aug 2016",
      actArrDate: "6 Aug 2016",
      actDepDate: "6 Aug 2016",
      dayDiff: "0",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 5
    }, {
      stnCode: "BAY",
      idTrnSch: "3372239",
      actArr: "09:45",
      actDep: "09:50",
      dayCnt: 2,
      schArrTime: "09:48",
      schDepTime: "09:50",
      schDayCnt: 2,
      delayArr: -3,
      delayDep: 0,
      arr: true,
      dep: true,
      distance: 1991,
      journeyDate: "6 Aug 2016",
      actArrDate: "6 Aug 2016",
      actDepDate: "6 Aug 2016",
      dayDiff: "0",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 1
    }, {
      stnCode: "MOMU",
      idTrnSch: "3372240",
      actArr: "11:10",
      actDep: "11:27",
      dayCnt: 2,
      schArrTime: "11:26",
      schDepTime: "11:27",
      schDayCnt: 2,
      delayArr: -16,
      delayDep: 0,
      arr: true,
      dep: true,
      distance: 2059,
      journeyDate: "6 Aug 2016",
      actArrDate: "6 Aug 2016",
      actDepDate: "6 Aug 2016",
      dayDiff: "0",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "THKU",
      idTrnSch: "",
      actArr: "11:54",
      actDep: "11:54",
      dayCnt: 2,
      schArrTime: "12:06",
      schDepTime: "12:06",
      schDayCnt: 2,
      delayArr: -12,
      delayDep: -12,
      arr: true,
      dep: true,
      distance: 2092,
      journeyDate: "6 Aug 2016",
      actArrDate: "6 Aug 2016",
      actDepDate: "6 Aug 2016",
      dayDiff: "0",
      stoppingStn: false,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "CHKE",
      idTrnSch: "3372241",
      actArr: "12:09",
      actDep: "12:10",
      dayCnt: 2,
      schArrTime: "12:09",
      schDepTime: "12:10",
      schDayCnt: 2,
      delayArr: 0,
      delayDep: 0,
      arr: false,
      dep: false,
      distance: 2107,
      journeyDate: "6 Aug 2016",
      actArrDate: "6 Aug 2016",
      actDepDate: "6 Aug 2016",
      dayDiff: "0",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "CTA",
      idTrnSch: "3372242",
      actArr: "12:43",
      actDep: "12:45",
      dayCnt: 2,
      schArrTime: "12:43",
      schDepTime: "12:45",
      schDayCnt: 2,
      delayArr: 0,
      delayDep: 0,
      arr: false,
      dep: false,
      distance: 2142,
      journeyDate: "6 Aug 2016",
      actArrDate: "6 Aug 2016",
      actDepDate: "6 Aug 2016",
      dayDiff: "0",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "RRB",
      idTrnSch: "3372243",
      actArr: "14:24",
      actDep: "14:25",
      dayCnt: 2,
      schArrTime: "14:24",
      schDepTime: "14:25",
      schDayCnt: 2,
      delayArr: 0,
      delayDep: 0,
      arr: false,
      dep: false,
      distance: 2244,
      journeyDate: "6 Aug 2016",
      actArrDate: "6 Aug 2016",
      actDepDate: "6 Aug 2016",
      dayDiff: "0",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "DRU",
      idTrnSch: "3372244",
      actArr: "14:34",
      actDep: "14:35",
      dayCnt: 2,
      schArrTime: "14:34",
      schDepTime: "14:35",
      schDayCnt: 2,
      delayArr: 0,
      delayDep: 0,
      arr: false,
      dep: false,
      distance: 2250,
      journeyDate: "6 Aug 2016",
      actArrDate: "6 Aug 2016",
      actDepDate: "6 Aug 2016",
      dayDiff: "0",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "ASK",
      idTrnSch: "3372245",
      actArr: "15:05",
      actDep: "15:10",
      dayCnt: 2,
      schArrTime: "15:05",
      schDepTime: "15:10",
      schDayCnt: 2,
      delayArr: 0,
      delayDep: 0,
      arr: false,
      dep: false,
      distance: 2289,
      journeyDate: "6 Aug 2016",
      actArrDate: "6 Aug 2016",
      actDepDate: "6 Aug 2016",
      dayDiff: "0",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "TK",
      idTrnSch: "3372246",
      actArr: "16:18",
      actDep: "16:20",
      dayCnt: 2,
      schArrTime: "16:18",
      schDepTime: "16:20",
      schDayCnt: 2,
      delayArr: 0,
      delayDep: 0,
      arr: false,
      dep: false,
      distance: 2385,
      journeyDate: "6 Aug 2016",
      actArrDate: "6 Aug 2016",
      actDepDate: "6 Aug 2016",
      dayDiff: "0",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "BAW",
      idTrnSch: "3372247",
      actArr: "17:14",
      actDep: "17:15",
      dayCnt: 2,
      schArrTime: "17:14",
      schDepTime: "17:15",
      schDayCnt: 2,
      delayArr: 0,
      delayDep: 0,
      arr: false,
      dep: false,
      distance: 2444,
      journeyDate: "6 Aug 2016",
      actArrDate: "6 Aug 2016",
      actDepDate: "6 Aug 2016",
      dayDiff: "0",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }, {
      stnCode: "YPR",
      idTrnSch: "3372248",
      actArr: "17:55",
      actDep: "00:00",
      dayCnt: 2,
      schArrTime: "17:55",
      schDepTime: "00:00",
      schDayCnt: 2,
      delayArr: 0,
      delayDep: 0,
      arr: false,
      dep: false,
      distance: 2452,
      journeyDate: "6 Aug 2016",
      actArrDate: "6 Aug 2016",
      actDepDate: "",
      dayDiff: "0",
      stoppingStn: true,
      dvrtdStn: false,
      travelled: true,
      updWaitngArr: false,
      updWaitngDep: false,
      pfNo: 0
    }],
    totalLateMins: 0,
    isRunningDataAvailable: true
  }]
}]